name: everyPush
on: [push]
# on:
#   schedule:
# * is a special character in YAML so you have to quote this string
#     - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Commit files
        run: |
          yarn install
          yarn test
        with:
          BILIBILI_COOKIE: ${{ secrets.BILIBILI_COOKIE }}
